version: '3.8'

services:
  genetic-algorithm:
    build:
      context: .
      dockerfile: Dockerfile  
    volumes:
      - .:/workspaces/protein-aggregation
    command: sleep infinity
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  esmfold-service:
    build:
      context: .
      dockerfile: Dockerfile.esmfold 
    ports:
      - "5001:5001"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]